version: '3.1'

services:

  mysql_easyclub:
#    image: mysql:8.0.32
    image: mysql:5.7.41
    container_name: mysql_easyclub
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easyclubdb
      MYSQL_PASSWORD: root
    ports:
      - "3366:3306"
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql_easyclub
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql_easyclub
      MYSQL_ROOT_PASSWORD: root

